# Project: qualysinhvien
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = nhapnode.o nhapSV.o main.o Xuat.o sapxep.o sua.o timkiem.o PhanloaiSV.o Xoa.o
LINKOBJ  = nhapnode.o nhapSV.o main.o Xuat.o sapxep.o sua.o timkiem.o PhanloaiSV.o Xoa.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = qualysinhvien.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

nhapnode.o: nhapnode.cpp
	$(CPP) -c nhapnode.cpp -o nhapnode.o $(CXXFLAGS)

nhapSV.o: nhapSV.cpp
	$(CPP) -c nhapSV.cpp -o nhapSV.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Xuat.o: Xuat.cpp
	$(CPP) -c Xuat.cpp -o Xuat.o $(CXXFLAGS)

sapxep.o: sapxep.cpp
	$(CPP) -c sapxep.cpp -o sapxep.o $(CXXFLAGS)

sua.o: sua.cpp
	$(CPP) -c sua.cpp -o sua.o $(CXXFLAGS)

timkiem.o: timkiem.cpp
	$(CPP) -c timkiem.cpp -o timkiem.o $(CXXFLAGS)

PhanloaiSV.o: PhanloaiSV.cpp
	$(CPP) -c PhanloaiSV.cpp -o PhanloaiSV.o $(CXXFLAGS)

Xoa.o: Xoa.cpp
	$(CPP) -c Xoa.cpp -o Xoa.o $(CXXFLAGS)
